Repository goorm-sudo/raillo-backend, pull requests merged in 2025-06, with the labels that each got.

#12 [FEATURE] 승차권 관련 Entity 설계 및 생성
  src/main/java/com/sudo/railo/ticket/domain/Qr.java
  src/main/java/com/sudo/railo/ticket/domain/Reservation.java
  src/main/java/com/sudo/railo/ticket/domain/ReservationStatus.java
  src/main/java/com/sudo/railo/ticket/domain/SeasonTicket.java
  src/main/java/com/sudo/railo/ticket/domain/SeasonTicketStatus.java
  src/main/java/com/sudo/railo/ticket/domain/Ticket.java
  src/main/java/com/sudo/railo/ticket/domain/TripType.java
Labels: ✨ feature

#24 [FEATURE] Swagger 설정 #23
  build.gradle
  src/main/java/com/sudo/railo/global/config/SwaggerConfig.java
Labels: ⚙️ chore, ✨ feature

#21 [FEATURE] 글로벌 예외 처리 구현
  src/main/java/com/sudo/railo/global/exception/ErrorTestController.java
  src/main/java/com/sudo/railo/global/exception/GlobalExceptionHandler.java
  src/main/java/com/sudo/railo/global/exception/TestRequestDTO.java
  src/main/java/com/sudo/railo/global/exception/error/BusinessException.java
  src/main/java/com/sudo/railo/global/exception/error/ErrorCode.java
  src/main/java/com/sudo/railo/global/exception/error/ErrorResponse.java
  src/main/java/com/sudo/railo/global/exception/error/GlobalError.java
  src/main/java/com/sudo/railo/member/exception/MemberError.java
Labels: ✨ feature

#27 [FEATURE] BaseEntity 구현
  src/main/java/com/sudo/railo/global/domain/BaseEntity.java
Labels: ✨ feature

#29 refactor: 승차권 엔티티 승차권 번호 관련 필드 이름 변경 (#28)
  src/main/java/com/sudo/railo/ticket/domain/Ticket.java
Labels: ♻️ refactor

#44 [FEATURE] 비회원 정보 저장 로직 구현
  src/main/java/com/sudo/railo/global/security/SecurityConfig.java
  src/main/java/com/sudo/railo/member/application/MemberService.java
  src/main/java/com/sudo/railo/member/application/MemberServiceImpl.java
  src/main/java/com/sudo/railo/member/application/dto/request/GuestRegisterRequest.java
  src/main/java/com/sudo/railo/member/application/dto/response/GuestRegisterResponse.java
  src/main/java/com/sudo/railo/member/domain/Member.java
  src/main/java/com/sudo/railo/member/exception/MemberError.java
  src/main/java/com/sudo/railo/member/infra/MemberRepository.java
  src/main/java/com/sudo/railo/member/presentation/MemberController.java
  src/main/java/com/sudo/railo/member/success/MemberSuccess.java
Labels: ✨ feature

#52 [CHORE] .editorconfig 추가
  .editorconfig
Labels: ⚙️ chore

#40 [FEATURE] 열차 운행 캘린더 조회
  src/main/java/com/sudo/railo/global/domain/YesNo.java
  src/main/java/com/sudo/railo/global/exception/error/GlobalError.java
  src/main/java/com/sudo/railo/train/application/TrainScheduleService.java
  src/main/java/com/sudo/railo/train/application/dto/request/OperationCalendarItem.java
  src/main/java/com/sudo/railo/train/application/dto/request/ScheduleSearchRequest.java
  src/main/java/com/sudo/railo/train/application/dto/response/TrainScheduleSuccess.java
  src/main/java/com/sudo/railo/train/domain/TrainSchedule.java
  src/main/java/com/sudo/railo/train/domain/status/OperationStatus.java
  src/main/java/com/sudo/railo/train/domain/type/BusinessDayType.java
  src/main/java/com/sudo/railo/train/infrastructure/TrainScheduleRepository.java
  src/main/java/com/sudo/railo/train/infrastructure/TrainScheduleRepositoryCustom.java
  src/main/java/com/sudo/railo/train/infrastructure/TrainScheduleRepositoryCustomImpl.java
  src/main/java/com/sudo/railo/train/presentation/TrainScheduleController.java
Labels: ✨ feature

#50 [FEATURE] 회원 정보 조회 및 삭제 로직 구현
  src/main/java/com/sudo/railo/global/security/jwt/TokenExtractor.java
  src/main/java/com/sudo/railo/member/application/MemberService.java
  src/main/java/com/sudo/railo/member/application/MemberServiceImpl.java
  src/main/java/com/sudo/railo/member/application/dto/response/MemberInfoResponse.java
  src/main/java/com/sudo/railo/member/exception/MemberError.java
  src/main/java/com/sudo/railo/member/presentation/MemberController.java
  src/main/java/com/sudo/railo/member/success/MemberSuccess.java
Labels: ✨ feature

#47 [FEATURE] KTX 열차시간표 파싱 로직 구현
  build.gradle
  src/main/java/com/sudo/railo/RailoApplication.java
  src/main/java/com/sudo/railo/train/application/StationService.java
  src/main/java/com/sudo/railo/train/application/TrainScheduleCreator.java
  src/main/java/com/sudo/railo/train/application/TrainService.java
  src/main/java/com/sudo/railo/train/application/dto/ScheduleStopData.java
  src/main/java/com/sudo/railo/train/application/dto/TrainData.java
  src/main/java/com/sudo/railo/train/application/dto/TrainScheduleData.java
  src/main/java/com/sudo/railo/train/config/TrainTemplateProperties.java
  src/main/java/com/sudo/railo/train/domain/ScheduleStop.java
  src/main/java/com/sudo/railo/train/domain/Seat.java
  src/main/java/com/sudo/railo/train/domain/Station.java
  src/main/java/com/sudo/railo/train/domain/Train.java
  src/main/java/com/sudo/railo/train/domain/TrainCar.java
  src/main/java/com/sudo/railo/train/domain/TrainSchedule.java
  src/main/java/com/sudo/railo/train/domain/type/TrainType.java
  src/main/java/com/sudo/railo/train/infrastructure/StationRepository.java
  src/main/java/com/sudo/railo/train/infrastructure/TrainRepository.java
  src/main/java/com/sudo/railo/train/infrastructure/excel/ExcelParser.java
  src/main/java/com/sudo/railo/train/infrastructure/excel/TrainScheduleParser.java
  src/main/java/com/sudo/railo/train/infrastructure/scheduler/TrainScheduler.java
  src/main/resources/train-template.yml
  src/test/java/com/sudo/railo/train/application/TrainScheduleCreatorTest.java
Labels: ✨ feature

#55 [FEATURE] AccessToken 재발급 로직 구현
  src/main/java/com/sudo/railo/global/security/TokenError.java
  src/main/java/com/sudo/railo/global/security/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/sudo/railo/global/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/sudo/railo/global/security/jwt/TokenProvider.java
  src/main/java/com/sudo/railo/member/application/MemberAuthService.java
  src/main/java/com/sudo/railo/member/application/MemberAuthServiceImpl.java
  src/main/java/com/sudo/railo/member/application/MemberService.java
  src/main/java/com/sudo/railo/member/application/MemberServiceImpl.java
  src/main/java/com/sudo/railo/member/application/dto/response/ReissueTokenResponse.java
  src/main/java/com/sudo/railo/member/docs/AuthControllerDocs.java
  src/main/java/com/sudo/railo/member/presentation/AuthController.java
  src/main/java/com/sudo/railo/member/presentation/MemberController.java
  src/main/java/com/sudo/railo/member/success/AuthSuccess.java
Labels: ✨ feature

#58 [FEATURE] KTX 운임표 파싱 로직 구현
  .gitignore
  src/main/java/com/sudo/railo/train/application/StationFareCreator.java
  src/main/java/com/sudo/railo/train/application/TrainScheduleCreator.java
  src/main/java/com/sudo/railo/train/application/TrainService.java
  src/main/java/com/sudo/railo/train/application/dto/excel/ScheduleStopData.java
  src/main/java/com/sudo/railo/train/application/dto/excel/StationFareData.java
  src/main/java/com/sudo/railo/train/application/dto/excel/StationFareHeader.java
  src/main/java/com/sudo/railo/train/application/dto/excel/StationFareHeaderType.java
  src/main/java/com/sudo/railo/train/application/dto/excel/TrainData.java
  src/main/java/com/sudo/railo/train/application/dto/excel/TrainScheduleData.java
  src/main/java/com/sudo/railo/train/domain/StationFare.java
  src/main/java/com/sudo/railo/train/infrastructure/TrainScheduleRepository.java
  src/main/java/com/sudo/railo/train/infrastructure/excel/ExcelParser.java
  src/main/java/com/sudo/railo/train/infrastructure/excel/StationFareParser.java
  src/main/java/com/sudo/railo/train/infrastructure/excel/TrainScheduleParser.java
  src/main/java/com/sudo/railo/train/infrastructure/scheduler/TrainScheduler.java
  src/main/java/com/sudo/railo/train/presentation/TrainTestController.java
  src/test/java/com/sudo/railo/train/application/TrainScheduleCreatorTest.java
Labels: ✨ feature

#69 feat: 열차 조회 응답에 trainScheduleId 추가 (#68)
  src/main/java/com/sudo/railo/train/application/TrainScheduleService.java
  src/main/java/com/sudo/railo/train/application/dto/response/TrainSearchResponse.java
Labels: ✨ feature
