Repository goorm-sudo/raillo-backend, pull requests merged in 2025-07, with the labels that each got.

#78 [CHORE] Prometheus 모니터링 연동
  build.gradle
  src/main/java/com/sudo/railo/global/security/SecurityConfig.java
Labels: ⚙️ chore

#87 [CHORE] Github Action CI/CD 스크립트 작성
  .github/workflows/deploy_raillo_with_k8s.yml
  .github/workflows/gradle_build_and_test.yml
Labels: ⚙️ chore

#90 [FEATURE] 예약 생성 로직 수정 및 추가 요청사항 반영
  src/main/java/com/sudo/railo/booking/application/FareCalculationService.java
  src/main/java/com/sudo/railo/booking/application/ReservationAllocationService.java
  src/main/java/com/sudo/railo/booking/application/ReservationApplicationService.java
  src/main/java/com/sudo/railo/booking/application/ReservationService.java
  src/main/java/com/sudo/railo/booking/application/SeatReservationService.java
  src/main/java/com/sudo/railo/booking/application/dto/request/FareCalculateRequest.java
  src/main/java/com/sudo/railo/booking/application/dto/request/ReservationCreateRequest.java
  src/main/java/com/sudo/railo/booking/application/dto/request/ReservationDeleteRequest.java
  src/main/java/com/sudo/railo/booking/application/dto/response/ReservationCreateResponse.java
  src/main/java/com/sudo/railo/booking/docs/ReservationControllerDocs.java
  src/main/java/com/sudo/railo/booking/domain/PassengerSummary.java
  src/main/java/com/sudo/railo/booking/domain/Reservation.java
  src/main/java/com/sudo/railo/booking/domain/SeatReservation.java
  src/main/java/com/sudo/railo/booking/exception/BookingError.java
  src/main/java/com/sudo/railo/booking/presentation/ReservationController.java
Labels: ✨ feature

#92 fix: cors 오리진 도메인 오타 수정
  src/main/resources/application-prod.yml
Labels: ⚙️ chore

#94 [CI] 트리거 브랜치 네이밍 오류 수정
  .github/workflows/gradle_build_and_test.yml
Labels: ⚙️ chore

#104 [CHORE] Prometheus 메트릭 수집을 위한 엔드포인트 활성화 설정 추가
  src/main/resources/application-prod.yml
Labels: ⚙️ chore

#105 [CHORE] Prometheus 엔드포인트 활성화 설정 추가, Action 브랜치 네이밍 오류 수정
  .github/workflows/gradle_build_and_test.yml
  src/main/resources/application-prod.yml
Labels: ⚙️ chore

#98 [FEATURE] 파싱 로직 성능 개선 및 수정
  src/main/java/com/sudo/railo/global/exception/GlobalExceptionHandler.java
  src/main/java/com/sudo/railo/global/security/SecurityConfig.java
  src/main/java/com/sudo/railo/train/application/ScheduleStopService.java
  src/main/java/com/sudo/railo/train/application/SeatService.java
  src/main/java/com/sudo/railo/train/application/StationFareCreator.java
  src/main/java/com/sudo/railo/train/application/StationService.java
  src/main/java/com/sudo/railo/train/application/TrainCarService.java
  src/main/java/com/sudo/railo/train/application/TrainScheduleCreator.java
  src/main/java/com/sudo/railo/train/application/TrainScheduleTemplateService.java
  src/main/java/com/sudo/railo/train/application/TrainScheduler.java
  src/main/java/com/sudo/railo/train/application/TrainService.java
  src/main/java/com/sudo/railo/train/application/dto/excel/TrainScheduleData.java
  src/main/java/com/sudo/railo/train/application/dto/response/TrainAdminSuccess.java
  src/main/java/com/sudo/railo/train/config/TrainTemplateProperties.java
  src/main/java/com/sudo/railo/train/domain/ScheduleStop.java
  src/main/java/com/sudo/railo/train/domain/ScheduleStopTemplate.java
  src/main/java/com/sudo/railo/train/domain/Seat.java
  src/main/java/com/sudo/railo/train/domain/Train.java
  src/main/java/com/sudo/railo/train/domain/TrainCar.java
  src/main/java/com/sudo/railo/train/domain/TrainSchedule.java
  src/main/java/com/sudo/railo/train/domain/TrainScheduleTemplate.java
  src/main/java/com/sudo/railo/train/infrastructure/ScheduleStopTemplateRepository.java
  src/main/java/com/sudo/railo/train/infrastructure/TrainCarRepository.java
  src/main/java/com/sudo/railo/train/infrastructure/TrainRepository.java
  src/main/java/com/sudo/railo/train/infrastructure/TrainScheduleRepository.java
  src/main/java/com/sudo/railo/train/infrastructure/TrainScheduleTemplateRepository.java
  src/main/java/com/sudo/railo/train/infrastructure/excel/StationFareParser.java
  src/main/java/com/sudo/railo/train/infrastructure/excel/TrainScheduleParser.java
  src/main/java/com/sudo/railo/train/infrastructure/jdbc/ScheduleStopJdbcRepository.java
  src/main/java/com/sudo/railo/train/infrastructure/jdbc/ScheduleStopJdbcRepositoryImpl.java
  src/main/java/com/sudo/railo/train/infrastructure/jdbc/TrainJdbcRepository.java
  src/main/java/com/sudo/railo/train/infrastructure/jdbc/TrainJdbcRepositoryImpl.java
  src/main/java/com/sudo/railo/train/infrastructure/jdbc/TrainScheduleJdbcRepository.java
  src/main/java/com/sudo/railo/train/infrastructure/jdbc/TrainScheduleJdbcRepositoryImpl.java
  src/main/java/com/sudo/railo/train/presentation/TrainAdminController.java
  src/main/java/com/sudo/railo/train/presentation/TrainTestController.java
  src/main/java/com/sudo/railo/train/util/OperatingDayUtil.java
  src/main/resources/application-prod.yml
Labels: ✨ feature

#109 [FEATURE] 임시토큰 접근 권한 수정
  src/main/java/com/sudo/railo/global/security/jwt/JwtFilter.java
  src/main/java/com/sudo/railo/global/security/jwt/TokenProvider.java
Labels: ✨ feature

#99 [FEATURE] 티켓, QR 생성 및 조회 로직 구현
  src/main/java/com/sudo/railo/booking/application/QrService.java
  src/main/java/com/sudo/railo/booking/application/ReservationApplicationService.java
  src/main/java/com/sudo/railo/booking/application/TicketService.java
  src/main/java/com/sudo/railo/booking/docs/TicketControllerDocs.java
  src/main/java/com/sudo/railo/booking/domain/Qr.java
  src/main/java/com/sudo/railo/booking/domain/Ticket.java
  src/main/java/com/sudo/railo/booking/exception/BookingError.java
  src/main/java/com/sudo/railo/booking/infra/QrRepository.java
  src/main/java/com/sudo/railo/booking/infra/TicketRepository.java
  src/main/java/com/sudo/railo/booking/presentation/ReservationController.java
  src/main/java/com/sudo/railo/booking/presentation/TicketController.java
  src/main/java/com/sudo/railo/booking/success/TicketSuccess.java
Labels: ✨ feature

#110 [FEATURE] 승차권 - 좌석 예약 현황 관계 추가 및 승차권 조회 로직 수정
  src/main/java/com/sudo/railo/booking/application/ReservationApplicationService.java
  src/main/java/com/sudo/railo/booking/application/TicketService.java
  src/main/java/com/sudo/railo/booking/domain/Ticket.java
Labels: ✨ feature

#102 [CHORE] ArgoCD 세팅
  k8s-argocd/argocd-application.yml
  k8s-argocd/argocd-https.yml
  k8s-argocd/argocd-ingress.yml
Labels: ⚙️ chore

#119 [CHORE] Prometheus – status 라벨 포함 및 5xx 에러율 분석 가능하게 설정
  src/main/java/com/sudo/railo/train/application/StationFareCreator.java
  src/main/java/com/sudo/railo/train/application/StationService.java
  src/main/java/com/sudo/railo/train/application/TrainScheduleCreator.java
  src/main/java/com/sudo/railo/train/application/TrainScheduleTemplateService.java
  src/main/resources/application-prod.yml
Labels: ⚙️ chore

#123 [RELEASE] 과도한 용량의 열차 관련 엑셀 파일을 최적화된 버전으로 교체
  files/station_fare.xls
  files/train_schedule.xlsx
Labels: 📝 docs

#125 [CHORE] #116 이슈 Revert 작업
  src/main/java/com/sudo/railo/train/application/StationFareCreator.java
  src/main/java/com/sudo/railo/train/application/StationService.java
  src/main/java/com/sudo/railo/train/application/TrainScheduleCreator.java
  src/main/java/com/sudo/railo/train/application/TrainScheduleTemplateService.java
Labels: ⚙️ chore

#126 [Release] 파싱 로직 Revert
  src/main/java/com/sudo/railo/train/application/StationFareCreator.java
  src/main/java/com/sudo/railo/train/application/StationService.java
  src/main/java/com/sudo/railo/train/application/TrainScheduleCreator.java
  src/main/java/com/sudo/railo/train/application/TrainScheduleTemplateService.java
Labels: 🐞 bug

#133 [FIX] Ticket 삭제 오류
  src/main/java/com/sudo/railo/booking/domain/Ticket.java
Labels: 🐞 bug

#140 [RELEASE] 상행 열차에서 구간 겹침 조건이 잘못되어 발생하는 좌석 조회 오류 해결
  src/main/java/com/sudo/railo/train/infrastructure/SeatReservationRepositoryCustomImpl.java
  src/main/java/com/sudo/railo/train/infrastructure/TrainCarQueryRepositoryCustomImpl.java
Labels: 🐞 bug

#142 [BUG] 자정을 넘는 열차 소요 시간 계산 오류, 상행 좌석 선택 오류
  src/main/java/com/sudo/railo/train/application/dto/response/TrainSearchResponse.java
  src/main/java/com/sudo/railo/train/infrastructure/SeatRepositoryCustomImpl.java
Labels: 🐞 bug

#143 [RELEASE] 음수 여행 소요 시간, 상행 노선 구간 좌석 상세 조회 오류 수정
  src/main/java/com/sudo/railo/train/application/dto/response/TrainSearchResponse.java
  src/main/java/com/sudo/railo/train/infrastructure/SeatRepositoryCustomImpl.java
Labels: 🐞 bug

#145 [FIX] 승차권 조회 시 과다 정보 노출 및 중첩
  src/main/java/com/sudo/railo/booking/application/TicketService.java
  src/main/java/com/sudo/railo/booking/application/dto/response/TicketReadResponse.java
  src/main/java/com/sudo/railo/booking/docs/TicketControllerDocs.java
  src/main/java/com/sudo/railo/booking/infra/TicketRepositoryCustom.java
  src/main/java/com/sudo/railo/booking/infra/TicketRepositoryCustomImpl.java
  src/main/java/com/sudo/railo/booking/presentation/TicketController.java
  src/main/java/com/sudo/railo/booking/success/TicketSuccess.java
Labels: 🔧 fix

#148 [FIX] 승차권, 예약 조회 시 잘못된 시간을 가져오는 이슈
  src/main/java/com/sudo/railo/booking/infra/ReservationRepositoryCustomImpl.java
  src/main/java/com/sudo/railo/booking/infra/TicketRepositoryCustomImpl.java
Labels: 🔧 fix

#157 [CHORE] Spring Pod 최대 메모리 제한 1GiB로 상향 조정
  k8s/depl_svc.yml
Labels: ⚙️ chore

#163 [REFACTOR] Booking 도메인 관련 엔티티 간소화
  src/main/java/com/sudo/railo/booking/application/ReservationApplicationService.java
  src/main/java/com/sudo/railo/booking/application/ReservationService.java
  src/main/java/com/sudo/railo/booking/application/SeatReservationService.java
  src/main/java/com/sudo/railo/booking/application/TicketService.java
  src/main/java/com/sudo/railo/booking/domain/PaymentStatus.java
  src/main/java/com/sudo/railo/booking/domain/Qr.java
  src/main/java/com/sudo/railo/booking/domain/Reservation.java
  src/main/java/com/sudo/railo/booking/domain/ReservationStatus.java
  src/main/java/com/sudo/railo/booking/domain/SeasonTicket.java
  src/main/java/com/sudo/railo/booking/domain/SeasonTicketStatus.java
  src/main/java/com/sudo/railo/booking/domain/SeatReservation.java
  src/main/java/com/sudo/railo/booking/domain/SeatStatus.java
  src/main/java/com/sudo/railo/booking/domain/Ticket.java
  src/main/java/com/sudo/railo/booking/domain/TicketType.java
  src/main/java/com/sudo/railo/booking/infra/ReservationRepositoryCustomImpl.java
  src/main/java/com/sudo/railo/booking/infra/SeatReservationRepository.java
  src/main/java/com/sudo/railo/booking/infra/TicketRepositoryCustomImpl.java
  src/main/java/com/sudo/railo/train/infrastructure/ScheduleStopRepository.java
  src/main/java/com/sudo/railo/train/infrastructure/SeatRepositoryCustomImpl.java
  src/main/java/com/sudo/railo/train/infrastructure/SeatReservationRepositoryCustomImpl.java
  src/main/java/com/sudo/railo/train/infrastructure/TrainCarQueryRepositoryCustomImpl.java
Labels: ♻️ refactor

#170 [REFACTOR] Booking 도메인 패키지 구조 개선
  src/main/java/com/sudo/railo/booking/application/CartReservationService.java
  src/main/java/com/sudo/railo/booking/application/FareCalculationService.java
  src/main/java/com/sudo/railo/booking/application/QrService.java
  src/main/java/com/sudo/railo/booking/application/ReservationApplicationService.java
  src/main/java/com/sudo/railo/booking/application/ReservationService.java
  src/main/java/com/sudo/railo/booking/application/SeatReservationService.java
  src/main/java/com/sudo/railo/booking/application/TicketService.java
  src/main/java/com/sudo/railo/booking/application/dto/projection/SeatReservationProjection.java
  src/main/java/com/sudo/railo/booking/application/dto/request/FareCalculateRequest.java
  src/main/java/com/sudo/railo/booking/application/dto/request/ReservationCreateRequest.java
  src/main/java/com/sudo/railo/booking/application/dto/response/SeatReservationDetail.java
  src/main/java/com/sudo/railo/booking/domain/Reservation.java
  src/main/java/com/sudo/railo/booking/domain/SeatReservation.java
  src/main/java/com/sudo/railo/booking/domain/Ticket.java
  src/main/java/com/sudo/railo/booking/domain/TripType.java
  src/main/java/com/sudo/railo/booking/domain/status/ReservationStatus.java
  src/main/java/com/sudo/railo/booking/domain/status/TicketStatus.java
  src/main/java/com/sudo/railo/booking/domain/type/PassengerSummary.java
  src/main/java/com/sudo/railo/booking/domain/type/PassengerType.java
  src/main/java/com/sudo/railo/booking/domain/type/TripType.java
  src/main/java/com/sudo/railo/booking/infrastructure/CartReservationRepository.java
  src/main/java/com/sudo/railo/booking/infrastructure/QrRepository.java
  src/main/java/com/sudo/railo/booking/infrastructure/SeatReservationRepository.java
  src/main/java/com/sudo/railo/booking/infrastructure/reservation/ReservationRepository.java
  src/main/java/com/sudo/railo/booking/infrastructure/reservation/ReservationRepositoryCustom.java
  src/main/java/com/sudo/railo/booking/infrastructure/reservation/ReservationRepositoryCustomImpl.java
  src/main/java/com/sudo/railo/booking/infrastructure/ticket/TicketRepository.java
  src/main/java/com/sudo/railo/booking/infrastructure/ticket/TicketRepositoryCustom.java
  src/main/java/com/sudo/railo/booking/infrastructure/ticket/TicketRepositoryCustomImpl.java
Labels: ♻️ refactor

#173 [REFACTOR] @OneToMany 제거
  src/main/java/com/sudo/railo/train/application/TrainService.java
  src/main/java/com/sudo/railo/train/domain/Train.java
  src/main/java/com/sudo/railo/train/domain/TrainCar.java
  src/main/java/com/sudo/railo/train/domain/TrainSchedule.java
  src/main/java/com/sudo/railo/train/infrastructure/TrainCarQueryRepositoryCustomImpl.java
  src/main/java/com/sudo/railo/train/infrastructure/TrainRepository.java
  src/main/java/com/sudo/railo/train/infrastructure/TrainScheduleRepositoryCustomImpl.java
Labels: ♻️ refactor

#179 [BUG] 로그아웃 시 Redis Duration 타입 직렬화/역직렬화 오류
  src/main/java/com/sudo/railo/global/config/RedisConfig.java
Labels: 🐞 bug

#180 [REFACTOR] Http only 적용
  src/main/java/com/sudo/railo/auth/application/AuthService.java
  src/main/java/com/sudo/railo/auth/application/dto/request/LoginRequest.java
  src/main/java/com/sudo/railo/auth/application/dto/response/LoginResponse.java
  src/main/java/com/sudo/railo/auth/docs/AuthControllerDocs.java
  src/main/java/com/sudo/railo/auth/exception/TokenError.java
  src/main/java/com/sudo/railo/auth/presentation/AuthController.java
  src/main/java/com/sudo/railo/auth/security/jwt/JwtFilter.java
  src/main/java/com/sudo/railo/auth/security/jwt/TokenProvider.java
  src/main/java/com/sudo/railo/auth/success/AuthSuccess.java
  src/main/java/com/sudo/railo/global/config/SecurityConfig.java
  src/main/java/com/sudo/railo/global/exception/GlobalExceptionHandler.java
Labels: ♻️ refactor

#182 [FIX] Booking 도메인 리팩토링 후 노선 중간 구간 예매 불가
  src/main/java/com/sudo/railo/booking/domain/SeatReservation.java
  src/main/java/com/sudo/railo/booking/domain/Ticket.java
  src/main/java/com/sudo/railo/train/infrastructure/SeatRepositoryCustomImpl.java
Labels: 🔧 fix

#184 [FEATURE] 로그아웃 시 Cookie에 담긴 refreshToken 만료 로직 추가
  src/main/java/com/sudo/railo/auth/docs/AuthControllerDocs.java
  src/main/java/com/sudo/railo/auth/presentation/AuthController.java
  src/main/java/com/sudo/railo/auth/util/CookieManager.java
Labels: ✨ feature

#189 [FEATURE] 운임 조회 로직 개선
  src/main/java/com/sudo/railo/booking/application/FareCalculationService.java
  src/main/java/com/sudo/railo/booking/application/ReservationService.java
  src/main/java/com/sudo/railo/booking/application/dto/ReservationInfo.java
  src/main/java/com/sudo/railo/booking/application/dto/projection/ReservationProjection.java
  src/main/java/com/sudo/railo/booking/application/dto/projection/SeatReservationProjection.java
  src/main/java/com/sudo/railo/booking/application/dto/request/FareCalculateRequest.java
  src/main/java/com/sudo/railo/booking/application/dto/response/ReservationDetail.java
  src/main/java/com/sudo/railo/booking/application/dto/response/SeatReservationDetail.java
  src/main/java/com/sudo/railo/booking/domain/Ticket.java
  src/main/java/com/sudo/railo/booking/exception/BookingError.java
  src/main/java/com/sudo/railo/booking/infrastructure/reservation/ReservationRepositoryCustomImpl.java
  src/main/java/com/sudo/railo/booking/presentation/BookingController.java
  src/main/java/com/sudo/railo/booking/success/FareSuccess.java
  src/main/java/com/sudo/railo/train/infrastructure/SeatRepository.java
Labels: ✨ feature

#192 [BUG] 좌석 충돌 예약 발생 오류
  src/main/java/com/sudo/railo/booking/application/ReservationService.java
  src/main/java/com/sudo/railo/booking/application/SeatReservationService.java
  src/main/java/com/sudo/railo/booking/domain/SeatReservation.java
  src/main/java/com/sudo/railo/booking/infrastructure/SeatReservationRepository.java
  src/main/java/com/sudo/railo/member/infrastructure/MemberRepositoryCustom.java
Labels: 🐞 bug
